const tilesCa = [
  { character: 'a', count: 12, score: 1 },
  { character: 'b', count: 2, score: 3 },
  { character: 'c', count: 3, score: 2 },
  { character: 'ç', count: 1, score: 10 },
  { character: 'd', count: 3, score: 2 },
  { character: 'e', count: 13, score: 1 },
  { character: 'f', count: 1, score: 4 },
  { character: 'g', count: 2, score: 3 },
  { character: 'h', count: 1, score: 8 },
  { character: 'i', count: 8, score: 1 },
  { character: 'j', count: 1, score: 8 },
  { character: 'l', count: 4, score: 1 },
  { character: 'l·l', count: 1, score: 10 },
  { character: 'm', count: 3, score: 2 },
  { character: 'n', count: 6, score: 1 },
  { character: 'ny', count: 1, score: 10 },
  { character: 'o', count: 5, score: 1 },
  { character: 'p', count: 2, score: 3 },
  { character: 'qu', count: 1, score: 8 },
  { character: 'r', count: 8, score: 1 },
  { character: 's', count: 8, score: 1 },
  { character: 't', count: 5, score: 1 },
  { character: 'u', count: 4, score: 1 },
  { character: 'v', count: 1, score: 4 },
  { character: 'x', count: 1, score: 10 },
  { character: 'z', count: 1, score: 8 },
];

export default tilesCa;
